config/routes.rb
Apple2hand::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users

  resources :products

  namespace :admin do
    resources :users
  end

  #root :to => 'high_voltage/pages#show', :id => 'welcome'
  root :to => "products#index"
  
end

app/models/area_data.rb
# -*- encoding : utf-8 -*-
class AreaData < Settingslogic
  source "#{Rails.root}/config/area_data.yml"
  namespace Rails.env
end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
end

app/models/product_data.rb
# -*- encoding : utf-8 -*-
class ProductData < Settingslogic
  source "#{Rails.root}/config/product_data.yml"
  namespace Rails.env
end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base


  extend OmniauthCallbacks
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :products
  
  def bind_service(response)
    # fb
    provider = response["provider"]
    uid = response["uid"]
    update_attribute(:fb_id, uid)
  end

  def facebook_user?
    fb_id.to_i > 0
  end


  def admin?
    return true if Setting.admin_emails.include?(self.email)
    return false
  end
end

app/models/user/omniauth_callbacks.rb
# -*- encoding : utf-8 -*-
class User
  module OmniauthCallbacks
    
      ["facebook"].each do |provider|
      define_method "find_or_create_for_#{provider}" do |response|
        uid = response["uid"]
        data = response["info"]
      
        credentials= response['credentials']

        if user = User.where( :fb_id => uid).first
          return user
        elsif user = User.find_by_email(data["email"])
          user.update_attribute(:fb_id ,uid )
          return user
        else
          user = User.new_from_provider_data(provider,uid,data, credentials)
          if user.save(:validate => false)
            user.fb_id = uid
            user.save
            return user
          else
            Rails.logger.warn("User.create_from_hash 失败，#{user.errors.inspect}")
            return nil
          end
        end
        
      end
    end
     
    
    def new_from_provider_data(provider, uid, data,credentials)
      user = User.new
      user.email = data["email"]
      user.token = credentials['token']
      user.name = data["nickname"] ? data ["nickname"] : data["name"]

      user.name.gsub!(/[^\w]/, "_")
      if User.where(:name => user.name).count > 0 || user.name.blank?
        user.name = "u#{Time.now.to_i}"
      end
      
      user.password = Devise.friendly_token[0,20]

      return user
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery

    def login_required
    if current_user.blank?
      respond_to do |format|
        format.html  {
          authenticate_user!
        }
        format.js{
          render :partial => "common/not_logined"
        }
        format.all { 
          head(:unauthorized)
        }
      end
    end
  end

 def require_is_admin
    unless (current_user && current_user.admin?)
      redirect_to root_path, :flash => { :error => "no permission" }
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :login_required, :only => [:new,:create,:edit,:update,:destroy]

  def new
    @product = current_user.products.build
  end


  def create
    @product = current_user.products.build(params[:product])
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = current_user.products.find(params[:id])

  end

  def update
    @product = current_user.products.find(params[:id])
    if product.update_attribute(params[:product])
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def index
    @products = Product.paginate( :page => params[:page], :per_page => 15 )
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# -*- encoding : utf-8 -*-
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(*providers)
    providers.each do |provider|
      class_eval %Q{
        def #{provider}
          if !current_user.blank?
            current_user.bind_service(env["omniauth.auth"])#Add an auth to existing
            redirect_to setting_path, :notice => "Bind #{provider} account successfully."
          else
            @user = User.find_or_create_for_#{provider}(env["omniauth.auth"])
  
            if @user.persisted?
             # flash[:notice] = "Signed in with #{provider.to_s.titleize} successfully."
              
              
              sign_in_and_redirect @user, :event => :authentication, :notice => "Signed in successfully."
            else
              redirect_to new_user_registration_url
            end
          end
        end
      }
    end
  end
  
  provides_callback_for :facebook

  # This is solution for existing accout want bind Google login but current_user is always nil
  # https://github.com/intridea/omniauth/issues/185
  def handle_unverified_request
    true
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_menu.html.erb
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="<%= admin_users_path %>">
         Admin
      </a>
      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("User", admin_users_path ) 
      end %>

    </li>

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=289554394417824";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <%= render_list :class => "nav nav-pills pull-right" do |li|
      #li << link_to( "Link1", "#")
      #li << link_to( "Link2", "#")   
      #li << link_to( "Link3", "#")
      #li << link_to( "Link4", "#")
  end %>
  <p class="copyright">Copyright @2012 <%= Setting.app_name %> All rights reserved.</p>

</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.erb
<div class="navbar navbar-fixed-top ">
      <div class="navbar-inner top ">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to(Setting.app_name, Setting.domain , :class => "brand" )%>

          <%= render :partial => "common/search_form" %>

   
     
          <div class="nav-collapse">
      
              <%= render_list :class => "nav" do |li|
                li << link_to("Link-1","Link-1")
                li << link_to("Link-2","Link-2")
                li << link_to("Link-3","Link-3")
              end %>
              
              <%= render :partial => "common/user_nav"%>

          </div>
    </div>
  </div>

  <%= yield :submenu %>

</div>

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">

    <li>
      <div class="social"> <%=  fb_like(Setting.domain) %>  </div>
    </li>

  <% if current_user %>
  
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="<%= user_path(current_user) %>">
          <%= current_user.name %>
      </a>
      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout",destroy_user_session_path, :method => :delete )
          li << link_to("Admin", admin_users_path ) if current_user.admin?
      end %>

    </li>

    <%= render :partial => "admin/menu" if current_user.admin? %>  



<% else %>
    <li> <%= link_to( "Login", "/users/auth/facebook" )  %> </li>
    
<% end %>

    <li> <%= link_to("About", "/pages/about") %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

<%= render :partial => "common/menu" %>

  <div class="container">

      <%= notice_message %>

      <div class="content">
        <div class="row">
          <%= yield %>
          <%= yield (:sidebar) %>
        </div> 
    
      </div>

      <%= render :partial => "common/footer" %>    
  </div>



  

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>

  <%= yield :javascripts %>


</body>
</html>

app/views/pages/welcome.html.erb
<div class="span12">
	<h1> Welcome </h1>
</div>

app/views/products/index.html.erb
<div class="span12">
  <div class="group pull-right">
    <%= link_to("刊登產品", new_product_path, :class => "btn btn-primary") %>
  </div>
</div>

app/views/products/new.html.erb
<div class="span12">
  <div class="box">
    <%= simple_form_for :product, :url => products_path do |f| %>
      <%= f.input :category_id, :as => :select, :collection => Category.all %> 
      <%= f.input :product_spec, :label => "物品規格", :input_html => { :class => "input-xxlarge", :rows => 10}, :placeholder => "MacBook Pro 13 吋 Retina 2012 款 8G RAM" %>

      <%= f.input :apple_care_expired_at, :as => :date, :start_year => Date.today.year - 15,
                              :end_year => Date.today.year + 3,
                              :order => [:day, :month, :year], :label => "保固日期" %>
      <%= f.input :has_invoice,     :as => :radio_buttons, :label => "原始發票" %>
      <%= f.input :accessories, :label => "隨機配件", :placeholder => "原廠盒裝配件" %>
      <%= f.input :description, :as => :text, :label => "物品敘述", :input_html => { :class => "input-xxlarge", :rows => 10} %>
      <%= f.input :extenal_link, :label => "物品連結", :input_html => { :class => "input-xxlarge"} , :placeholder => "http://tw.bid.yahoo/xxxxx" %>
      <%= f.input :trade_area, :as => :select, :collection => AreaData.county_codes,  :label => "交易地區" %>
      <%= f.input :trade_type, :as => :select, :collection => ProductData.trade_types, :label => "交易方式" %>
      <%= f.input :trade_price, :label => "交易價格" %>
      <%= f.input :extra_note, :as => :text ,:label => "其他備註", :input_html => { :class => "input-xxlarge", :rows => 10} %>

      <div class="form-actions">
        <%= f.submit "Submit", :disable_with => 'Submiting...' , :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>